project_id = "bvmuhjppqreyyoavowya"

[functions.server-status]
verify_jwt = false

[functions.admin-setup]
verify_jwt = false

[functions.classify-mods]
verify_jwt = false

[functions.moderate-content]
verify_jwt = false

